import { MushiConfig, CharacterPresetId } from './mushi';

export const CHARACTER_PRESETS: Record<CharacterPresetId, MushiConfig> = {
  custom: {
    seed: 'CUSTOM-01',
    name: 'Custom Den Den Mushi',
    presetId: 'custom',
    modelMode: 'procedural',
    region: 'east_blue',
    personality: 'cheerful',
    face: {
      eyeShape: 'round',
      eyeSize: 1.0,
      eyeSpacing: 1.0,
      eyeHeight: 1.0,
      pupilStyle: 'large',
      pupilColor: '#0f172a',
      eyebrowStyle: 'thick',
      eyebrowAngle: 0,
      mouthStyle: 'smile',
      cheekStyle: 'none',
      expression: 'happy',
      facialHair: 'none',
      glasses: 'none',
      noseStyle: 'normal'
    },
    body: {
      bodyColor: '#4ade80',
      skinPattern: 'plain',
      patternColor: '#ffffff',
      bodyScale: 1.0,
      bodyWidth: 1.0,
      antennaLength: 1.0,
      antennaCurve: 1.0,
      neckAccessory: 'none'
    },
    shell: {
      shellShape: 'classic_spiral',
      primaryColor: '#f97316',
      secondaryColor: '#ffffff',
      dialColor: '#d4af37',
      pattern: 'spiral',
      wearLevel: 0.1,
      hasRotaryDial: true,
      receiverOnTop: true,
      hasKeypad: false,
      hasTopCameraLens: false
    },
    accessory: 'none',
    voice: { pitch: 1.0, rate: 1.0, pitchShiftName: 'normal' }
  },

  whitebeard: {
    seed: 'WHITEBEARD-01',
    name: 'Whitebeard Den Den Mushi',
    presetId: 'whitebeard',
    modelMode: 'procedural',
    region: 'pirate',
    personality: 'emperor',
    face: {
      eyeShape: 'narrow',
      eyeSize: 1.05,
      eyeSpacing: 1.0,
      eyeHeight: 1.0,
      pupilStyle: 'small',
      pupilColor: '#1e293b',
      eyebrowStyle: 'angled',
      eyebrowAngle: 10,
      mouthStyle: 'toothy_grin',
      cheekStyle: 'none',
      expression: 'confident',
      facialHair: 'whitebeard_crescent',
      glasses: 'none',
      noseStyle: 'normal'
    },
    body: {
      bodyColor: '#fef3c7',
      skinPattern: 'plain',
      patternColor: '#ffffff',
      bodyScale: 1.1,
      bodyWidth: 1.15,
      antennaLength: 1.1,
      antennaCurve: 0.9,
      neckAccessory: 'none'
    },
    shell: {
      shellShape: 'whitebeard_headset',
      primaryColor: '#881337',
      secondaryColor: '#d97706',
      dialColor: '#94a3b8',
      pattern: 'flames',
      wearLevel: 0.2,
      hasRotaryDial: false,
      receiverOnTop: true,
      hasKeypad: false,
      hasTopCameraLens: false
    },
    accessory: 'whitebeard_mustache',
    voice: { pitch: 0.65, rate: 0.9, pitchShiftName: 'low', laughSound: 'Gurararara!' }
  },

  doflamingo: {
    seed: 'DOFLAMINGO-01',
    name: 'Doflamingo Den Den Mushi',
    presetId: 'doflamingo',
    modelMode: 'procedural',
    region: 'pirate',
    personality: 'sinister',
    face: {
      eyeShape: 'doflamingo_shades',
      eyeSize: 1.2,
      eyeSpacing: 1.05,
      eyeHeight: 1.0,
      pupilStyle: 'small',
      pupilColor: '#000000',
      eyebrowStyle: 'none',
      eyebrowAngle: 0,
      mouthStyle: 'toothy_grin',
      cheekStyle: 'none',
      expression: 'sinister',
      facialHair: 'none',
      glasses: 'doflamingo_red',
      noseStyle: 'normal'
    },
    body: {
      bodyColor: '#ec4899',
      skinPattern: 'plain',
      patternColor: '#ffffff',
      bodyScale: 1.05,
      bodyWidth: 1.0,
      antennaLength: 1.15,
      antennaCurve: 1.1,
      neckAccessory: 'pink_feather_coat'
    },
    shell: {
      shellShape: 'classic_spiral',
      primaryColor: '#be123c',
      secondaryColor: '#f472b6',
      dialColor: '#d4af37',
      pattern: 'spiral',
      wearLevel: 0.1,
      hasRotaryDial: true,
      receiverOnTop: true,
      hasKeypad: false,
      hasTopCameraLens: false
    },
    accessory: 'pink_feather_boa',
    voice: { pitch: 1.15, rate: 1.1, pitchShiftName: 'high', laughSound: 'Fuffuffuffu!' }
  },

  vegapunk: {
    seed: 'VEGAPUNK-01',
    name: 'Vegapunk SSG Video Mushi',
    presetId: 'vegapunk',
    modelMode: 'procedural',
    region: 'water_7',
    personality: 'curious',
    face: {
      eyeShape: 'droopy',
      eyeSize: 1.1,
      eyeSpacing: 1.1,
      eyeHeight: 1.05,
      pupilStyle: 'large',
      pupilColor: '#1e3a8a',
      eyebrowStyle: 'flat',
      eyebrowAngle: 0,
      mouthStyle: 'duck_bill',
      cheekStyle: 'none',
      expression: 'curious',
      facialHair: 'none',
      glasses: 'none',
      noseStyle: 'normal'
    },
    body: {
      bodyColor: '#fef08a',
      skinPattern: 'plain',
      patternColor: '#ffffff',
      bodyScale: 1.0,
      bodyWidth: 1.1,
      antennaLength: 1.1,
      antennaCurve: 0.9,
      neckAccessory: 'none'
    },
    shell: {
      shellShape: 'vegapunk_camera',
      primaryColor: '#18181b',
      secondaryColor: '#f472b6',
      dialColor: '#eab308',
      pattern: 'stripes',
      wearLevel: 0.05,
      hasRotaryDial: false,
      receiverOnTop: false,
      hasKeypad: true,
      hasTopCameraLens: true
    },
    accessory: 'vegapunk_lens',
    voice: { pitch: 1.0, rate: 1.15, pitchShiftName: 'normal' }
  },

  luffy: {
    seed: 'LUFFY-01',
    name: 'Luffy Straw Hat Mushi',
    presetId: 'luffy',
    modelMode: 'procedural',
    region: 'east_blue',
    personality: 'cheerful',
    face: {
      eyeShape: 'round',
      eyeSize: 1.25,
      eyeSpacing: 1.0,
      eyeHeight: 1.0,
      pupilStyle: 'large',
      pupilColor: '#0f172a',
      eyebrowStyle: 'thick',
      eyebrowAngle: -5,
      mouthStyle: 'smile',
      cheekStyle: 'eye_scar',
      expression: 'happy',
      facialHair: 'none',
      glasses: 'none',
      noseStyle: 'normal'
    },
    body: {
      bodyColor: '#fbbf24',
      skinPattern: 'plain',
      patternColor: '#ffffff',
      bodyScale: 1.0,
      bodyWidth: 1.0,
      antennaLength: 1.0,
      antennaCurve: 1.0,
      neckAccessory: 'none'
    },
    shell: {
      shellShape: 'classic_spiral',
      primaryColor: '#dc2626',
      secondaryColor: '#fef08a',
      dialColor: '#d4af37',
      pattern: 'spiral',
      wearLevel: 0.1,
      hasRotaryDial: true,
      receiverOnTop: true,
      hasKeypad: false,
      hasTopCameraLens: false
    },
    accessory: 'straw_hat',
    voice: { pitch: 1.25, rate: 1.2, pitchShiftName: 'high', laughSound: 'Shishishi!' }
  },

  law: {
    seed: 'LAW-01',
    name: 'Law Heart Pirates Mushi',
    presetId: 'law',
    modelMode: 'glb_law',
    region: 'pirate',
    personality: 'serious',
    face: {
      eyeShape: 'narrow',
      eyeSize: 0.95,
      eyeSpacing: 1.0,
      eyeHeight: 0.95,
      pupilStyle: 'small',
      pupilColor: '#0f172a',
      eyebrowStyle: 'angled',
      eyebrowAngle: 12,
      mouthStyle: 'frown',
      cheekStyle: 'none',
      expression: 'suspicious',
      facialHair: 'mihawk_goatee',
      glasses: 'none',
      noseStyle: 'normal'
    },
    body: {
      bodyColor: '#fef08a',
      skinPattern: 'spots',
      patternColor: '#1e293b',
      bodyScale: 1.0,
      bodyWidth: 1.0,
      antennaLength: 1.05,
      antennaCurve: 0.9,
      neckAccessory: 'law_collar'
    },
    shell: {
      shellShape: 'classic_spiral',
      primaryColor: '#1e3a8a',
      secondaryColor: '#eab308',
      dialColor: '#94a3b8',
      pattern: 'heart_jolly',
      wearLevel: 0.2,
      hasRotaryDial: true,
      receiverOnTop: true,
      hasKeypad: false,
      hasTopCameraLens: false
    },
    accessory: 'law_spotted_hat',
    voice: { pitch: 0.75, rate: 0.95, pitchShiftName: 'low' }
  },

  mihawk: {
    seed: 'MIHAWK-01',
    name: 'Mihawk Hawk-Eyes Mushi',
    presetId: 'mihawk',
    modelMode: 'procedural',
    region: 'royal',
    personality: 'serious',
    face: {
      eyeShape: 'hawk_eyes',
      eyeSize: 1.0,
      eyeSpacing: 1.0,
      eyeHeight: 1.0,
      pupilStyle: 'hawk',
      pupilColor: '#eab308',
      eyebrowStyle: 'angled',
      eyebrowAngle: 14,
      mouthStyle: 'frown',
      cheekStyle: 'none',
      expression: 'serious',
      facialHair: 'mihawk_goatee',
      glasses: 'none',
      noseStyle: 'normal'
    },
    body: {
      bodyColor: '#cbd5e1',
      skinPattern: 'plain',
      patternColor: '#ffffff',
      bodyScale: 1.0,
      bodyWidth: 1.0,
      antennaLength: 1.1,
      antennaCurve: 0.9,
      neckAccessory: 'none'
    },
    shell: {
      shellShape: 'classic_spiral',
      primaryColor: '#450a0a',
      secondaryColor: '#ca8a04',
      dialColor: '#d4af37',
      pattern: 'solid',
      wearLevel: 0.1,
      hasRotaryDial: true,
      receiverOnTop: true,
      hasKeypad: false,
      hasTopCameraLens: false
    },
    accessory: 'royal_crown',
    voice: { pitch: 0.65, rate: 0.85, pitchShiftName: 'low' }
  },

  crocodile: {
    seed: 'CROCODILE-01',
    name: 'Crocodile Baroque Mushi',
    presetId: 'crocodile',
    modelMode: 'procedural',
    region: 'pirate',
    personality: 'sinister',
    face: {
      eyeShape: 'narrow',
      eyeSize: 0.9,
      eyeSpacing: 1.0,
      eyeHeight: 0.95,
      pupilStyle: 'small',
      pupilColor: '#000000',
      eyebrowStyle: 'angled',
      eyebrowAngle: 15,
      mouthStyle: 'cigar_mouth',
      cheekStyle: 'scars',
      expression: 'sinister',
      facialHair: 'none',
      glasses: 'none',
      noseStyle: 'normal'
    },
    body: {
      bodyColor: '#e2e8f0',
      skinPattern: 'stripes',
      patternColor: '#334155',
      bodyScale: 1.05,
      bodyWidth: 1.1,
      antennaLength: 1.1,
      antennaCurve: 0.85,
      neckAccessory: 'none'
    },
    shell: {
      shellShape: 'ridged_shell',
      primaryColor: '#1e293b',
      secondaryColor: '#ca8a04',
      dialColor: '#d4af37',
      pattern: 'stripes',
      wearLevel: 0.3,
      hasRotaryDial: true,
      receiverOnTop: true,
      hasKeypad: false,
      hasTopCameraLens: false
    },
    accessory: 'croc_cigar',
    voice: { pitch: 0.7, rate: 0.85, pitchShiftName: 'low', laughSound: 'Kuhahaha!' }
  },

  ivankov: {
    seed: 'IVANKOV-01',
    name: 'Ivankov Okama Mushi',
    presetId: 'ivankov',
    modelMode: 'procedural',
    region: 'royal',
    personality: 'dramatic',
    face: {
      eyeShape: 'large',
      eyeSize: 1.3,
      eyeSpacing: 1.0,
      eyeHeight: 1.1,
      pupilStyle: 'ring',
      pupilColor: '#c084fc',
      eyebrowStyle: 'curved',
      eyebrowAngle: -10,
      mouthStyle: 'big_lipstick',
      cheekStyle: 'soft_blush',
      expression: 'surprised',
      facialHair: 'none',
      glasses: 'none',
      noseStyle: 'normal'
    },
    body: {
      bodyColor: '#c084fc',
      skinPattern: 'plain',
      patternColor: '#ffffff',
      bodyScale: 1.15,
      bodyWidth: 1.2,
      antennaLength: 1.2,
      antennaCurve: 1.2,
      neckAccessory: 'none'
    },
    shell: {
      shellShape: 'classic_spiral',
      primaryColor: '#9333ea',
      secondaryColor: '#f472b6',
      dialColor: '#fef08a',
      pattern: 'swirl',
      wearLevel: 0.1,
      hasRotaryDial: true,
      receiverOnTop: true,
      hasKeypad: false,
      hasTopCameraLens: false
    },
    accessory: 'headset',
    voice: { pitch: 1.35, rate: 1.3, pitchShiftName: 'high', laughSound: 'Hee-Haw!' }
  },

  smoker: {
    seed: 'SMOKER-01',
    name: 'Smoker Marine Mushi',
    presetId: 'smoker',
    modelMode: 'procedural',
    region: 'marine',
    personality: 'serious',
    face: {
      eyeShape: 'angry',
      eyeSize: 0.9,
      eyeSpacing: 1.0,
      eyeHeight: 0.9,
      pupilStyle: 'small',
      pupilColor: '#0f172a',
      eyebrowStyle: 'angled',
      eyebrowAngle: 18,
      mouthStyle: 'cigar_mouth',
      cheekStyle: 'none',
      expression: 'angry',
      facialHair: 'none',
      glasses: 'none',
      noseStyle: 'normal'
    },
    body: {
      bodyColor: '#5eead4',
      skinPattern: 'plain',
      patternColor: '#ffffff',
      bodyScale: 1.05,
      bodyWidth: 1.1,
      antennaLength: 1.0,
      antennaCurve: 0.9,
      neckAccessory: 'marine_coat'
    },
    shell: {
      shellShape: 'ridged_shell',
      primaryColor: '#475569',
      secondaryColor: '#cbd5e1',
      dialColor: '#1e3a8a',
      pattern: 'solid',
      wearLevel: 0.4,
      hasRotaryDial: true,
      receiverOnTop: true,
      hasKeypad: false,
      hasTopCameraLens: false
    },
    accessory: 'smoker_cigars',
    voice: { pitch: 0.6, rate: 0.9, pitchShiftName: 'low' }
  },

  kizaru: {
    seed: 'KIZARU-01',
    name: 'Kizaru Admiral Mushi',
    presetId: 'kizaru',
    modelMode: 'procedural',
    region: 'marine',
    personality: 'sleepy',
    face: {
      eyeShape: 'sleepy',
      eyeSize: 1.0,
      eyeSpacing: 1.0,
      eyeHeight: 0.9,
      pupilStyle: 'small',
      pupilColor: '#0f172a',
      eyebrowStyle: 'flat',
      eyebrowAngle: 0,
      mouthStyle: 'oval',
      cheekStyle: 'none',
      expression: 'sleepy',
      facialHair: 'thin_mustache',
      glasses: 'kizaru_tinted',
      noseStyle: 'normal'
    },
    body: {
      bodyColor: '#fef08a',
      skinPattern: 'stripes',
      patternColor: '#ca8a04',
      bodyScale: 1.0,
      bodyWidth: 1.0,
      antennaLength: 1.1,
      antennaCurve: 1.0,
      neckAccessory: 'marine_coat'
    },
    shell: {
      shellShape: 'classic_spiral',
      primaryColor: '#eab308',
      secondaryColor: '#ffffff',
      dialColor: '#1e3a8a',
      pattern: 'stripes',
      wearLevel: 0.1,
      hasRotaryDial: true,
      receiverOnTop: true,
      hasKeypad: false,
      hasTopCameraLens: false
    },
    accessory: 'marine_hat',
    voice: { pitch: 0.8, rate: 0.7, pitchShiftName: 'low' }
  },

  buggy: {
    seed: 'BUGGY-01',
    name: 'Buggy Clown Mushi',
    presetId: 'buggy',
    modelMode: 'procedural',
    region: 'pirate',
    personality: 'goofy',
    face: {
      eyeShape: 'wide',
      eyeSize: 1.2,
      eyeSpacing: 1.05,
      eyeHeight: 1.0,
      pupilStyle: 'ring',
      pupilColor: '#dc2626',
      eyebrowStyle: 'curved',
      eyebrowAngle: -10,
      mouthStyle: 'toothy_grin',
      cheekStyle: 'soft_blush',
      expression: 'happy',
      facialHair: 'none',
      glasses: 'none',
      noseStyle: 'red_clown_nose'
    },
    body: {
      bodyColor: '#bfdbfe',
      skinPattern: 'spots',
      patternColor: '#ef4444',
      bodyScale: 1.0,
      bodyWidth: 1.0,
      antennaLength: 1.1,
      antennaCurve: 1.1,
      neckAccessory: 'none'
    },
    shell: {
      shellShape: 'classic_spiral',
      primaryColor: '#dc2626',
      secondaryColor: '#2563eb',
      dialColor: '#eab308',
      pattern: 'stripes',
      wearLevel: 0.2,
      hasRotaryDial: true,
      receiverOnTop: true,
      hasKeypad: false,
      hasTopCameraLens: false
    },
    accessory: 'clown_nose',
    voice: { pitch: 1.3, rate: 1.25, pitchShiftName: 'high', laughSound: 'Gyahahahaha!' }
  },

  franky: {
    seed: 'FRANKY-01',
    name: 'Franky Super Mushi',
    presetId: 'franky',
    modelMode: 'procedural',
    region: 'water_7',
    personality: 'cheerful',
    face: {
      eyeShape: 'wide',
      eyeSize: 1.1,
      eyeSpacing: 1.0,
      eyeHeight: 1.0,
      pupilStyle: 'large',
      pupilColor: '#0f172a',
      eyebrowStyle: 'thick',
      eyebrowAngle: -8,
      mouthStyle: 'toothy_grin',
      cheekStyle: 'star_tattoos',
      expression: 'confident',
      facialHair: 'none',
      glasses: 'cyborg_shades',
      noseStyle: 'normal'
    },
    body: {
      bodyColor: '#38bdf8',
      skinPattern: 'plain',
      patternColor: '#ffffff',
      bodyScale: 1.1,
      bodyWidth: 1.15,
      antennaLength: 1.0,
      antennaCurve: 1.0,
      neckAccessory: 'none'
    },
    shell: {
      shellShape: 'armored_plates',
      primaryColor: '#0284c7',
      secondaryColor: '#fbbf24',
      dialColor: '#dc2626',
      pattern: 'solid',
      wearLevel: 0.1,
      hasRotaryDial: true,
      receiverOnTop: true,
      hasKeypad: false,
      hasTopCameraLens: false
    },
    accessory: 'franky_hair',
    voice: { pitch: 0.85, rate: 1.1, pitchShiftName: 'normal', laughSound: 'SUUUUPER!' }
  },

  marine_officer: {
    seed: 'MARINE-01',
    name: 'Marine HQ Mushi',
    presetId: 'marine_officer',
    modelMode: 'procedural',
    region: 'marine',
    personality: 'formal',
    face: {
      eyeShape: 'oval',
      eyeSize: 1.0,
      eyeSpacing: 1.0,
      eyeHeight: 1.0,
      pupilStyle: 'large',
      pupilColor: '#0f172a',
      eyebrowStyle: 'flat',
      eyebrowAngle: 0,
      mouthStyle: 'smile',
      cheekStyle: 'none',
      expression: 'neutral',
      facialHair: 'none',
      glasses: 'none',
      noseStyle: 'normal'
    },
    body: {
      bodyColor: '#93c5fd',
      skinPattern: 'plain',
      patternColor: '#ffffff',
      bodyScale: 1.0,
      bodyWidth: 1.0,
      antennaLength: 1.0,
      antennaCurve: 1.0,
      neckAccessory: 'marine_coat'
    },
    shell: {
      shellShape: 'classic_spiral',
      primaryColor: '#1e3a8a',
      secondaryColor: '#ffffff',
      dialColor: '#d4af37',
      pattern: 'spiral',
      wearLevel: 0.05,
      hasRotaryDial: true,
      receiverOnTop: true,
      hasKeypad: false,
      hasTopCameraLens: false
    },
    accessory: 'marine_hat',
    voice: { pitch: 1.0, rate: 1.0, pitchShiftName: 'normal' }
  },

  buster_call: {
    seed: 'BUSTER-01',
    name: 'Golden Buster Call Mushi',
    presetId: 'buster_call',
    modelMode: 'procedural',
    region: 'golden_buster',
    personality: 'serious',
    face: {
      eyeShape: 'angry',
      eyeSize: 1.0,
      eyeSpacing: 1.0,
      eyeHeight: 1.0,
      pupilStyle: 'small',
      pupilColor: '#dc2626',
      eyebrowStyle: 'angled',
      eyebrowAngle: 15,
      mouthStyle: 'frown',
      cheekStyle: 'none',
      expression: 'angry',
      facialHair: 'none',
      glasses: 'none',
      noseStyle: 'normal'
    },
    body: {
      bodyColor: '#fbbf24',
      skinPattern: 'plain',
      patternColor: '#ffffff',
      bodyScale: 1.05,
      bodyWidth: 1.05,
      antennaLength: 1.0,
      antennaCurve: 0.9,
      neckAccessory: 'none'
    },
    shell: {
      shellShape: 'ridged_shell',
      primaryColor: '#eab308',
      secondaryColor: '#dc2626',
      dialColor: '#dc2626',
      pattern: 'solid',
      wearLevel: 0.0,
      hasRotaryDial: true,
      receiverOnTop: true,
      hasKeypad: false,
      hasTopCameraLens: false
    },
    accessory: 'headset',
    voice: { pitch: 0.7, rate: 0.9, pitchShiftName: 'low' }
  }
};
